### ISSUE TITLE
basic tests fail on deb 8 and deb 9

### ISSUE THREAD

**Issue by tbrowder** [zoffixznet/perl6-Proc-Q#3]
deb 8: 
```
$ perl6 -v
This is Rakudo version 2017.11-36-g78caeb6 built on MoarVM version 2017.11
implementing Perl 6.c.
```

deb 9:
```
$ perl6 -v
This is Rakudo version 2018.02.1 built on MoarVM version 2018.02
implementing Perl 6.c.
```

**Comment by zoffixznet** [comment]
That's why there's a message saying the tests can fail on slow boxes. Just install without the tests.

**Comment by tbrowder** [comment]
But it seems to me that may be the cause of my toaster problems.  Do you have any idea why the tests fail on a slow box? 

What, then, is a "fast" box? My deb 8 box takes about 90 sec on rakudo stage parse while the deb 9 box takes about 150 sec.

**Comment by zoffixznet** [comment]
Because they're time sensitive tests that rely on multiple cores processing simultaneously. If you don't have enough cores to do it, they'll show up as not having killed the procs.

**Comment by tbrowder** [comment]
Any idea of min cores needed?  Can the proc be modified to go serial if not enough cores?  I'm willing to experiment but need a bit of guidance.  (BTW, I just got a faster box with more cores.)
